# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'canbusSniffer.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_canbusSniffer(object):
    def setupUi(self, canbusSniffer):
        canbusSniffer.setObjectName("canbusSniffer")
        canbusSniffer.resize(530, 770)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(canbusSniffer.sizePolicy().hasHeightForWidth())
        canbusSniffer.setSizePolicy(sizePolicy)
        canbusSniffer.setMinimumSize(QtCore.QSize(530, 770))
        canbusSniffer.setMaximumSize(QtCore.QSize(530, 770))
        self.layoutWidget = QtWidgets.QWidget(canbusSniffer)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 511, 731))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.canbusSelect = QtWidgets.QComboBox(self.layoutWidget)
        self.canbusSelect.setObjectName("canbusSelect")
        self.horizontalLayout.addWidget(self.canbusSelect)
        self.canbusSpeed = QtWidgets.QComboBox(self.layoutWidget)
        self.canbusSpeed.setObjectName("canbusSpeed")
        self.canbusSpeed.addItem("")
        self.canbusSpeed.addItem("")
        self.canbusSpeed.addItem("")
        self.horizontalLayout.addWidget(self.canbusSpeed)
        self.canbusStatus = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canbusStatus.sizePolicy().hasHeightForWidth())
        self.canbusStatus.setSizePolicy(sizePolicy)
        self.canbusStatus.setText("")
        self.canbusStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.canbusStatus.setObjectName("canbusStatus")
        self.horizontalLayout.addWidget(self.canbusStatus)
        self.canbusSetStatus = QtWidgets.QPushButton(self.layoutWidget)
        self.canbusSetStatus.setObjectName("canbusSetStatus")
        self.horizontalLayout.addWidget(self.canbusSetStatus)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.canbusDataReceived = QtWidgets.QTableWidget(self.layoutWidget)
        self.canbusDataReceived.setMinimumSize(QtCore.QSize(0, 500))
        self.canbusDataReceived.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.canbusDataReceived.setAutoScrollMargin(2)
        self.canbusDataReceived.setRowCount(1)
        self.canbusDataReceived.setColumnCount(10)
        self.canbusDataReceived.setObjectName("canbusDataReceived")
        item = QtWidgets.QTableWidgetItem()
        self.canbusDataReceived.setItem(0, 0, item)
        self.canbusDataReceived.horizontalHeader().setVisible(True)
        self.canbusDataReceived.horizontalHeader().setDefaultSectionSize(50)
        self.canbusDataReceived.horizontalHeader().setHighlightSections(True)
        self.canbusDataReceived.horizontalHeader().setMinimumSectionSize(50)
        self.canbusDataReceived.verticalHeader().setVisible(False)
        self.canbusDataReceived.verticalHeader().setMinimumSectionSize(21)
        self.verticalLayout.addWidget(self.canbusDataReceived)
        self.canbusReceivePacket = QtWidgets.QPushButton(self.layoutWidget)
        self.canbusReceivePacket.setCheckable(False)
        self.canbusReceivePacket.setObjectName("canbusReceivePacket")
        self.verticalLayout.addWidget(self.canbusReceivePacket)
        self.canbusPacketToSend = QtWidgets.QTableWidget(self.layoutWidget)
        self.canbusPacketToSend.setMaximumSize(QtCore.QSize(510, 50))
        self.canbusPacketToSend.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.canbusPacketToSend.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.canbusPacketToSend.setRowCount(1)
        self.canbusPacketToSend.setColumnCount(10)
        self.canbusPacketToSend.setObjectName("canbusPacketToSend")
        self.canbusPacketToSend.horizontalHeader().setDefaultSectionSize(50)
        self.canbusPacketToSend.horizontalHeader().setMinimumSectionSize(50)
        self.canbusPacketToSend.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.canbusPacketToSend)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.canbusSendPacket = QtWidgets.QPushButton(self.layoutWidget)
        self.canbusSendPacket.setObjectName("canbusSendPacket")
        self.horizontalLayout_2.addWidget(self.canbusSendPacket)
        self.canbusSendingPacket = QtWidgets.QPushButton(self.layoutWidget)
        self.canbusSendingPacket.setObjectName("canbusSendingPacket")
        self.horizontalLayout_2.addWidget(self.canbusSendingPacket)
        self.canbusSendingDelay = QtWidgets.QSpinBox(self.layoutWidget)
        self.canbusSendingDelay.setMinimum(1)
        self.canbusSendingDelay.setObjectName("canbusSendingDelay")
        self.horizontalLayout_2.addWidget(self.canbusSendingDelay)
        self.canbusSendingDelayLabel = QtWidgets.QLabel(self.layoutWidget)
        self.canbusSendingDelayLabel.setObjectName("canbusSendingDelayLabel")
        self.horizontalLayout_2.addWidget(self.canbusSendingDelayLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(canbusSniffer)
        QtCore.QMetaObject.connectSlotsByName(canbusSniffer)

    def retranslateUi(self, canbusSniffer):
        _translate = QtCore.QCoreApplication.translate
        canbusSniffer.setWindowTitle(_translate("canbusSniffer", "CAN BUS Sniffer"))
        self.canbusSpeed.setItemText(0, _translate("canbusSniffer", "115200"))
        self.canbusSpeed.setItemText(1, _translate("canbusSniffer", "230400"))
        self.canbusSpeed.setItemText(2, _translate("canbusSniffer", "460800"))
        self.canbusSetStatus.setText(_translate("canbusSniffer", "Connect"))
        __sortingEnabled = self.canbusDataReceived.isSortingEnabled()
        self.canbusDataReceived.setSortingEnabled(False)
        self.canbusDataReceived.setSortingEnabled(__sortingEnabled)
        self.canbusReceivePacket.setText(_translate("canbusSniffer", "Receive"))
        self.canbusSendPacket.setText(_translate("canbusSniffer", "Send"))
        self.canbusSendingPacket.setText(_translate("canbusSniffer", "Keep sending every"))
        self.canbusSendingDelayLabel.setText(_translate("canbusSniffer", "uS"))
